### ISSUE TITLE
Nuget package out of date.

### ISSUE THREAD

**Issue by martindevans** [smeshlink/CoAP.NET#17]
I submitted [this](https://github.com/smeshlink/CoAP.NET/pull/14) pull request a while ago. However, it seems that this hasn't been pushed out to nuget yet. Could you update the nuget package to a newer version?

**Comment by longshine** [comment]
Sorry for not updating the package. I will publish a new release in a few days.

**Comment by martindevans** [comment]
Thanks :D

-----Original Message-----

**Comment by longshine** [comment]
Fixed at 8464c5e6fe1fcd279ca4829736451625f845898b.

Proxy namespace has a separate package now.
