### ISSUE TITLE
Blockwise transfer for PUT requests

### ISSUE THREAD

**Issue by billpratt** [smeshlink/CoAP.NET#3]
Does this library allow for blockwise transfers as described here: http://www.google.com/url?q=http%3A%2F%2Ftools.ietf.org%2Fhtml%2Fdraft-ietf-core-block-08&sa=D&sntz=1&usg=AFQjCNGpPAnNm15802QG7Kgw_7iJ0BWuPw

**Comment by SachinEdwin** [comment]
whats the approach for blockwise GET request?
