### ISSUE TITLE
F# Interactive client with 4.05 status

### ISSUE THREAD

**Issue by caxelrud** [smeshlink/CoAP.NET#31]
I successfully created and communicated with the demo server, a COMPILED F# CoAP clients based on the examples as DISCOVER coap://localhost and GET coap://localhost/hello. 
But when I try the exact same code using F# interactive (REPL), I get: "Status : 4.05 Method Not Allowed". 
Also, I did the same test, but using a CoAP server in F# interactive with the same behavior. 
I am looking for suggestions why this is happening and how is the best way to debug the problem.

**Comment by longshine** [comment]
Hi~

I wrote some test code and did not reproduce the issue you found. Could you please share more details?

Here is my code:

```fsharp
#if INTERACTIVE
#r @"Path\To\CoAP.NET.dll"
#endif

open CoAP
open CoAP.Util

let req = Request.NewGet()
let uri = System.Uri("coap://localhost/hello")
req.URI <- uri

let res = req.Send().WaitForResponse()

if res = null
then System.Console.WriteLine("Request timeout")
else System.Console.WriteLine(Utils.ToString(res))
```

And I got **ACK 2.05 Content** both in a compiled project and in F# interactive (inside VS).

**Comment by caxelrud** [comment]
Thanks for reply. Sorry, but I had a bug in the F# interactive version. Now
all work well.

**Comment by longshine** [comment]
: )
