### ISSUE TITLE
Invalid getter for ProxyUri and ProxyScheme?

### ISSUE THREAD

**Issue by SiMet** [smeshlink/CoAP.NET#44]
Hi,

I've just found in class Message that getters for ProxyUri and ProxyScheme get option OptionType.Accept but set valid option.

Is that correct? 

I was very surprised when I set option Accept and the Utlis.OptionsToString returned something in ProxyScheme.

**Comment by longshine** [comment]
Oops... These are no doubt careless miswrittens in class `Message`. Would you like make a pull request and help us fix this? Or you can wait a couple of days before we have some new commit.
