### ISSUE TITLE
CoAP.net logging

### ISSUE THREAD

**Issue by DukeRIch** [smeshlink/CoAP.NET#46]
Is there any available documentation on logging? All the flags seem to be set off by default. I am confused as to how to activate them. Does app config need to be modified?

Thanks,

David

**Comment by longshine** [comment]
Hi~

CoAP.NET uses [Common.Logging .NET](https://github.com/net-commons/common-logging) for logging.
Please refer to its [documentation](https://github.com/net-commons/common-logging#2-register-and-configure-commonlogging) to see how to enable logging with it.

For example, you will see logs in your console after adding the contents below to your app.config:

```xml
  <configSections>
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
  </configSections>

  <common>
    <logging>
      <factoryAdapter type="Common.Logging.Simple.ConsoleOutLoggerFactoryAdapter, Common.Logging">
        <arg key="level" value="INFO" />
        <arg key="showLogName" value="true" />
        <arg key="showDateTime" value="true" />
        <arg key="dateTimeFormat" value="yyyy/MM/dd HH:mm:ss:fff" />
      </factoryAdapter>
    </logging>
  </common>
```

By default, if the Common.Logging dll exists but no config is found in app.config, the logging will be switched off.

If you'd like to see logs quickly, just remove the Common.Logging dll from your binary folder, and then logs should be on the console. In this case you may set log levels via `LogManager.Level`.

**Comment by DukeRIch** [comment]
Thank you for the prompt reply, that was exactly what I was looking for!
